{"pageProps":{"metadata":{"title":"Python基礎文法 - 後期","curriculumId":"1ada501e-f337-81d0-93c4-cc25006a2031","category":"後期","visibility":["基礎班","発展班"],"tags":["基礎班","Python"],"is_basic_curriculum":true,"id":"124"},"mdBlocks":[{"blockId":"1ada501e-f337-81ff-b119-c45a3dd5b185","type":"paragraph","parent":"今回はPythonの「例外処理」について説明します。","children":[]},{"blockId":"1ada501e-f337-814f-9e3f-c9d789b16424","type":"heading_2","parent":"## 例外処理の基本：try、except","children":[]},{"blockId":"1ada501e-f337-8113-8b9c-c2679892a4c8","type":"divider","parent":"---","children":[]},{"blockId":"1ada501e-f337-818a-9bc1-e05723af2966","type":"paragraph","parent":"Pythonの例外処理は、プログラムの実行中に発生するエラーを適切に扱い、プログラムのクラッシュを防ぐための仕組みです。","children":[]},{"blockId":"1ada501e-f337-81cf-8937-ecbcfd02d25b","type":"paragraph","parent":"例外処理を行うには、`try`、`except`を使います。","children":[]},{"blockId":"1ada501e-f337-8193-9d25-c00ba5c8dcde","type":"callout","parent":"{\"icon\":{\"type\":\"external\",\"external\":{\"url\":\"https://www.notion.so/icons/code_gray.svg\"}},\"color\":\"default_background\",\"parent\":\"> ### 基本構文  \\n>   \\n> ```python  \\n> try:  \\n> \\tエラーの可能性のある処理  \\n> except 想定されるエラー:  \\n> \\tエラーが起こった場合の処理  \\n> ```\"}","children":[{"blockId":"1ada501e-f337-81ae-934d-eb8d18e52d88","type":"heading_3","parent":"### 基本構文","children":[]},{"blockId":"1ada501e-f337-8175-8cda-ed135e652fad","type":"code","parent":"```python\ntry:\n\tエラーの可能性のある処理\nexcept 想定されるエラー:\n\tエラーが起こった場合の処理\n```","children":[]}]},{"blockId":"1ada501e-f337-81e2-bfa4-e75d5af66b01","type":"paragraph","parent":"例えば、ゼロによる除算が行われると`ZeroDivisionError`というエラーが発生して処理が終了します。`try`、`except`を使うとそのようなエラーが起こった場合の処理を書くことができます。","children":[]},{"blockId":"1ada501e-f337-818e-b5df-f60591106917","type":"callout","parent":"{\"icon\":{\"type\":\"external\",\"external\":{\"url\":\"https://www.notion.so/icons/code_gray.svg\"}},\"color\":\"default_background\",\"parent\":\"> ### 例  \\n>   \\n> ```python  \\n> a = 1  \\n> b = 0  \\n>   \\n> try:  \\n>     print(a / b)  \\n> except ZeroDivisionError:  \\n>     print('Error')  \\n> ```\"}","children":[{"blockId":"1ada501e-f337-816b-9c54-ce30983e7eeb","type":"heading_3","parent":"### 例","children":[]},{"blockId":"1ada501e-f337-8187-aafb-f34ca95b7f35","type":"code","parent":"```python\na = 1\nb = 0\n\ntry:\n    print(a / b)\nexcept ZeroDivisionError:\n    print('Error')\n```","children":[]}]},{"blockId":"1ada501e-f337-81f2-bb5a-cdc11dfc90e9","type":"paragraph","parent":"この例では、`a`を`b`で割り算しています。`b`が`0`でない場合は割り算の答えが`print関数`で出力され、`b`が`0`だった場合は`Error`と出力されます。そして、このコードでは`b = 0`なので以下のように出力されます。","children":[]},{"blockId":"1ada501e-f337-81bf-ae28-c5bcc52f9237","type":"callout","parent":"{\"icon\":{\"type\":\"external\",\"external\":{\"url\":\"https://www.notion.so/icons/share_gray.svg\"}},\"color\":\"default_background\",\"parent\":\"> 出力  \\n> ```bash  \\n> Error  \\n> ```\"}","children":[{"blockId":"1ada501e-f337-8144-bd87-d195386e448c","type":"code","parent":"```bash\nError\n```","children":[]}]},{"blockId":"1ada501e-f337-81c6-82ab-ec853b3c7176","type":"paragraph","parent":"さらに、`except 例外名 as 変数名:`とすると、変数にエラーを格納して使用できる。変数名は任意の名前を指定できるが、`e`や`err`といった名前が使われることが多い。","children":[]},{"blockId":"1ada501e-f337-81fe-92a5-e2841d9e4f1a","type":"callout","parent":"{\"icon\":{\"type\":\"external\",\"external\":{\"url\":\"https://www.notion.so/icons/code_gray.svg\"}},\"color\":\"default_background\",\"parent\":\"> ### エラーを変数に格納する  \\n>   \\n> ```python  \\n> a = 1  \\n> b = 0  \\n>   \\n> try:  \\n>     print(a / b)  \\n> **except ZeroDivisionError as e:  \\n>     print('Error')  \\n>     print(e)**  \\n> ```\"}","children":[{"blockId":"1ada501e-f337-8150-ad3f-cca6ca38704f","type":"heading_3","parent":"### エラーを変数に格納する","children":[]},{"blockId":"1ada501e-f337-81fb-821d-f97ec48f8e2a","type":"code","parent":"```python\na = 1\nb = 0\n\ntry:\n    print(a / b)\n**except ZeroDivisionError as e:\n    print('Error')\n    print(e)**\n```","children":[]}]},{"blockId":"1ada501e-f337-81e4-afe5-ed1e09688808","type":"paragraph","parent":"このように書くと、以下のようにエラーが出力されます。","children":[]},{"blockId":"1ada501e-f337-8119-9885-c3b00ffe49d9","type":"callout","parent":"{\"icon\":{\"type\":\"external\",\"external\":{\"url\":\"https://www.notion.so/icons/share_gray.svg\"}},\"color\":\"default_background\",\"parent\":\"> 出力  \\n> ```bash  \\n> Error  \\n> division by zero  \\n> ```\"}","children":[{"blockId":"1ada501e-f337-814a-8844-d85476aedf15","type":"code","parent":"```bash\nError\ndivision by zero\n```","children":[]}]},{"blockId":"1ada501e-f337-8138-b4dd-dc2b60e839ad","type":"heading_2","parent":"## 正常終了時の処理：else","children":[]},{"blockId":"1ada501e-f337-81c0-9df5-f9bf2e8786c6","type":"divider","parent":"---","children":[]},{"blockId":"1ada501e-f337-811a-8c51-cd82d6364313","type":"paragraph","parent":"`try`節で例外が発生せず正常終了したあとに行う処理を`else`節に指定できる。例外が発生して`except`で例外処理をした場合は`else`節の処理は実行されません。","children":[]},{"blockId":"1ada501e-f337-81ef-a7c9-e6be671cfb53","type":"callout","parent":"{\"icon\":{\"type\":\"external\",\"external\":{\"url\":\"https://www.notion.so/icons/code_gray.svg\"}},\"color\":\"default_background\",\"parent\":\"> ### 正常終了した場合の処理を書く  \\n>   \\n> ```python  \\n> a = 20  \\n> b = 5  \\n>   \\n> try:  \\n>     result = a / b  \\n> except ZeroDivisionError as e:  \\n>     print('Error:', e)  \\n> **else:  \\n> \\tprint(\\\"success:\\\", result)**  \\n> ```\"}","children":[{"blockId":"1ada501e-f337-8154-b435-f3a90c386196","type":"heading_3","parent":"### 正常終了した場合の処理を書く","children":[]},{"blockId":"1ada501e-f337-8104-8cb5-d84751cafd19","type":"code","parent":"```python\na = 20\nb = 5\n\ntry:\n    result = a / b\nexcept ZeroDivisionError as e:\n    print('Error:', e)\n**else:\n\tprint(\"success:\", result)**\n```","children":[]}]},{"blockId":"1ada501e-f337-81d6-8c81-ff9a791a3119","type":"paragraph","parent":"この場合、`try`節で`result = a / b`の処理がされます。`b=0`の場合は`except`節の処理が行われますが、今回は`b = 5`なので、`else`節の処理が行われ、以下のように出力されます。","children":[]},{"blockId":"1ada501e-f337-8153-81bd-fedf1c51f1fb","type":"callout","parent":"{\"icon\":{\"type\":\"external\",\"external\":{\"url\":\"https://www.notion.so/icons/share_gray.svg\"}},\"color\":\"default_background\",\"parent\":\"> 出力  \\n> ```bash  \\n> success: 4  \\n> ```\"}","children":[{"blockId":"1ada501e-f337-818e-99de-e72888b08035","type":"code","parent":"```bash\nsuccess: 4\n```","children":[]}]},{"blockId":"1ada501e-f337-8198-8d16-f3a5722df2b3","type":"heading_2","parent":"## **終了時に常に行う処理： finally**","children":[]},{"blockId":"1ada501e-f337-816e-b4b9-caac29f982cd","type":"divider","parent":"---","children":[]},{"blockId":"1ada501e-f337-81e4-addb-c998f42bcdb4","type":"paragraph","parent":"例外が発生した場合もしなかった場合も常に最後に行う処理を`finally`節に指定できます。","children":[]},{"blockId":"1ada501e-f337-8191-aab6-c2d676b419a2","type":"callout","parent":"{\"icon\":{\"type\":\"external\",\"external\":{\"url\":\"https://www.notion.so/icons/code_gray.svg\"}},\"color\":\"default_background\",\"parent\":\"> ### 終了時に常に行う処理を書く  \\n>   \\n> ```python  \\n> a = 20  \\n> b = 5  \\n>   \\n> try:  \\n>     result = a / b  \\n> except ZeroDivisionError as e:  \\n>     print('Error:', e)  \\n> else:  \\n> \\tprint(\\\"success:\\\", result)  \\n> **finally:  \\n> \\tprint(\\\"finish\\\")**  \\n> ```\"}","children":[{"blockId":"1ada501e-f337-8118-a291-e58b2f9b7808","type":"heading_3","parent":"### 終了時に常に行う処理を書く","children":[]},{"blockId":"1ada501e-f337-81be-9054-f2d91df3038b","type":"code","parent":"```python\na = 20\nb = 5\n\ntry:\n    result = a / b\nexcept ZeroDivisionError as e:\n    print('Error:', e)\nelse:\n\tprint(\"success:\", result)\n**finally:\n\tprint(\"finish\")**\n```","children":[]}]},{"blockId":"1ada501e-f337-8160-99a8-caf6cbc751e6","type":"paragraph","parent":"この場合、`try`節で`result = a / b`の処理がされます。`b`の値が`0`か否かで`except`節の処理か`else`節の処理が行われますが、いずれの場合でも`finally`節の処理、`print(”finish”)` が行われます。","children":[]},{"blockId":"1ada501e-f337-812b-9596-e52ffe2c8bb2","type":"paragraph","parent":"このコードの場合は`b=5`なので、以下のように出力されます。","children":[]},{"blockId":"1ada501e-f337-81bf-a571-cfcf8d0af4fd","type":"callout","parent":"{\"icon\":{\"type\":\"external\",\"external\":{\"url\":\"https://www.notion.so/icons/share_gray.svg\"}},\"color\":\"default_background\",\"parent\":\"> 出力  \\n> ```bash  \\n> success: 4  \\n> finish  \\n> ```\"}","children":[{"blockId":"1ada501e-f337-8196-9ac2-d2f614e14903","type":"code","parent":"```bash\nsuccess: 4\nfinish\n```","children":[]}]}],"pageNavs":[{"title":"Home","id":"/posts"},{"title":"基礎班カリキュラム","id":"/posts/course/basic"},{"title":"後期","id":"/posts/course/後期"},{"title":"Python基礎文法 - 後期","id":"/posts/curriculums/1ada501e-f337-81d0-93c4-cc25006a2031/1ada501e-f337-81d0-93c4-cc25006a2031"},{"id":"/posts/curriculums/1ada501e-f337-81d0-93c4-cc25006a2031/1ada501e-f337-81f8-bf0d-eb68b3253fce","title":"例外処理"}],"childrenData":{"title":"Python基礎文法 - 後期","childPages":[{"title":"import文","id":"1ada501e-f337-8176-9896-f0815ebd1e1c"},{"title":"クラスの継承","id":"1ada501e-f337-8139-983b-df7225049e88"},{"title":"文字列の中に変数を埋め込む","id":"1ada501e-f337-812d-a298-f72af5ac68d6"},{"title":"lambda式","id":"1ada501e-f337-81ec-b2e6-e054e5b77d29"},{"title":"例外処理","id":"1ada501e-f337-81f8-bf0d-eb68b3253fce"}]},"pageId":"1ada501e-f337-81f8-bf0d-eb68b3253fce","title":"例外処理"},"__N_SSG":true}